version: '3.7'
services:
  debian:
    build:
      context: docker
      dockerfile: Dockerfile.debian
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./:/usr/src/myapp
    environment:
      TEST_PHP_ARGS: "-q"
  alpine:
    build:
      context: docker
      dockerfile: Dockerfile.alpine
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./:/usr/src/myapp
    environment:
      TEST_PHP_ARGS: "-q"
