services:
  debian:
    image: opentelemetry-php-instrumentation:${PHP_VERSION:-8.3.10}-debian
    build:
      context: docker
      dockerfile: Dockerfile.debian
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3.10}
    volumes:
      - ./ext:/usr/src/myapp
    environment:
      TEST_PHP_ARGS: "-q"
  alpine:
    image: opentelemetry-php-instrumentation:${PHP_VERSION:-8.3.10}-alpine
    build:
      context: docker
      dockerfile: Dockerfile.alpine
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3.10}
    volumes:
      - ./ext:/usr/src/myapp
    environment:
      TEST_PHP_ARGS: "-q"
  32bit:
    image: opentelemetry-php-instrumentation:${PHP_VERSION:-8.4.0beta4}-alpine-i386
    build:
      context: docker
      dockerfile: Dockerfile.alpine
      args:
        ALPINE_VERSION: i386/alpine
        PHP_VERSION: ${PHP_VERSION:-8.4.0beta4}
    volumes:
      - ./ext:/usr/src/myapp
    environment:
      TEST_PHP_ARGS: "-q"
